"""Stage a watched run: the shipped 1993 binary and this reconstruction, side
by side under DOSBox-X.

    python runtest.py            stage run/ and launch DOSBox-X
    python runtest.py --print    stage run/ and print the command instead

WHY IT EXISTS. A part's rung moves on somebody WATCHING it -- no instrument
here can say whether the demo looks right, and `observe.py` exists to refuse a
run nobody made. This stages the one directory that makes the comparison
cheap: both executables and the data files they read, mounted as C:, so a
person can run ORIG, then OURS, and see the difference for themselves.

NO MACHINE PATHS. DOSBox-X's location comes from kit.local.toml, which git
ignores, and the .conf is GENERATED into run/ for the same reason -- a
committed .conf would carry this machine's paths. run/ is disposable and
gitignored; everything in it is copied from bin/ and build/.

A STALE REBUILD IS REFUSED rather than run. Measuring or watching a build that
is older than the sources it claims to be tells you about the wrong program,
and this is the one check that cannot be done afterwards -- once you have
watched it you believe it.
"""
import io
import pathlib
import shutil
import subprocess
import sys

import tomllib

ROOT = pathlib.Path(__file__).resolve().parent
RUN = ROOT / "run"

# name in run/  <- source. The originals keep their shipped names because the
# demo opens them by name; only the executables are renamed, so the two can
# sit in one directory.
STAGE = [
    ("SOFTEL.DAT", ROOT / "bin" / "SOFTEL.DAT"),
    ("SOFTEL.OVL", ROOT / "bin" / "SOFTEL.OVL"),
    ("PATEGA.MOD", ROOT / "bin" / "PATEGA.MOD"),
    ("ORIG.EXE", ROOT / "bin" / "SOFTEL.EXE"),
    ("OURS.EXE", ROOT / "build" / "SOFTEL.EXE"),
]

RUN_BAT = """\
@echo off
if "%1"=="" goto help
if "%1"=="ORIG" goto orig
if "%1"=="orig" goto orig
if "%1"=="OURS" goto ours
if "%1"=="ours" goto ours
goto help
:orig
echo --- the SHIPPED 1993 binary, bin/SOFTEL.EXE ---
ORIG.EXE
goto done
:ours
echo --- this RECONSTRUCTION, build/SOFTEL.EXE ---
OURS.EXE
goto done
:help
echo.
echo   RUN ORIG    the shipped 1993 binary
echo   RUN OURS    this reconstruction
echo.
echo Both read SOFTEL.DAT, SOFTEL.OVL and PATEGA.MOD from this directory.
echo Answer Y at the prompt for music. Any key starts the fade to the credits.
echo.
:done
"""

CONF = """\
# GENERATED by runtest.py. Edit kit.local.toml, never this file.
[sdl]
autolock=false
[dosbox]
memsize=16
[cpu]
core=auto
cycles=fixed 20000
[autoexec]
mount c "{run}"
c:
cls
call RUN.BAT
"""


def machine(key):
    f = ROOT / "kit.local.toml"
    if not f.is_file():
        sys.exit("  no kit.local.toml -- it holds this machine's paths and is "
                 "not committed. See CLAUDE.md.")
    d = tomllib.load(io.open(f, "rb"))
    section, _, name = key.partition(".")
    try:
        return d[section][name]
    except KeyError:
        sys.exit("  kit.local.toml does not answer %s" % key)


def stale():
    """Sources newer than the rebuilt executable, if any."""
    exe = ROOT / "build" / "SOFTEL.EXE"
    if not exe.is_file():
        return ["build/SOFTEL.EXE does not exist -- run build.py first"]
    cut = exe.stat().st_mtime
    return ["src/%s is newer than the build" % p.name
            for p in sorted((ROOT / "src").glob("*.PAS"))
            if p.stat().st_mtime > cut]


def main(argv):
    bad = stale()
    if bad:
        print("  REFUSING to stage a stale run:")
        for line in bad:
            print("    %s" % line)
        print("    Watching the wrong program is not a measurement you can "
              "take back.")
        return 2

    RUN.mkdir(exist_ok=True)
    for name, src in STAGE:
        if not src.is_file():
            print("  missing %s" % src.relative_to(ROOT))
            return 2
        shutil.copy(src, RUN / name)
    io.open(RUN / "RUN.BAT", "w", encoding="ascii", newline="\r\n").write(RUN_BAT)

    conf = RUN / "DOSBOX.CONF"
    io.open(conf, "w", encoding="ascii", newline="\r\n").write(
        CONF.format(run=str(RUN)))

    print("  staged run/ :")
    for name, src in STAGE:
        print("    %-12s %7d  <- %s"
              % (name, (RUN / name).stat().st_size, src.relative_to(ROOT)))
    print("    RUN.BAT, DOSBOX.CONF   generated")

    exe = machine("dosbox.exe")
    cmd = [str(exe), "-conf", str(conf)]
    if "--print" in argv:
        print("\n  " + " ".join('"%s"' % c if " " in c else c for c in cmd))
        return 0
    print("\n  launching DOSBox-X. Type RUN ORIG or RUN OURS.")
    return subprocess.call(cmd, cwd=str(RUN))


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
