"""Stage a watched run: the shipped 1993 binary and this reconstruction, side
by side under DOSBox-X on R:.

    python runtest.py            stage run/ and launch DOSBox-X
    python runtest.py --print    stage run/ and print the command instead

Either way it writes run/GO.BAT, which launches DOSBox-X on its own -- that is
the file to double-click or to run again later without going through Python.

WHAT YOU GET: an interactive session sitting at R:\\, with both executables and
the three data files they read. Type ORIG or OURS. There is deliberately no
dispatcher batch inside DOSBox -- the point is a prompt, not a menu.

WHY IT EXISTS. A part's rung moves on somebody WATCHING it. No instrument here
can say whether the demo looks right, and `observe.py` exists to refuse a run
nobody made.

NO MACHINE PATHS ARE COMMITTED. DOSBox-X's location comes from kit.local.toml,
which git ignores, and both the .conf and GO.BAT are GENERATED into run/ for
the same reason. run/ is disposable and gitignored; everything in it is copied
from bin/ and build/.

A STALE REBUILD IS REFUSED rather than staged. Watching a build older than the
sources it claims to be tells you about the wrong program, and it is the one
error you cannot take back -- once you have seen it, you believe it.
"""
import io
import pathlib
import shutil
import subprocess
import sys

import tomllib

ROOT = pathlib.Path(__file__).resolve().parent
RUN = ROOT / "run"

# name in run/  <- source. The data files keep their shipped names because the
# demo opens them by name; only the executables are renamed, so both can sit
# in one directory.
STAGE = [
    ("SOFTEL.DAT", ROOT / "bin" / "SOFTEL.DAT"),
    ("SOFTEL.OVL", ROOT / "bin" / "SOFTEL.OVL"),
    ("PATEGA.MOD", ROOT / "bin" / "PATEGA.MOD"),
    ("ORIG.EXE", ROOT / "bin" / "SOFTEL.EXE"),
    ("OURS.EXE", ROOT / "build" / "SOFTEL.EXE"),
]

# Mounted as R: and left at the prompt. `cycles=fixed 20000` is roughly the
# 386 speed README.1ST asks for -- Denthor's note says GoldPlay's own advice
# is wrong and "about 20khz for a 386 is about right".
CONF = """\
# GENERATED by runtest.py. Edit kit.local.toml or runtest.py, never this file.
[sdl]
autolock=false
[dosbox]
memsize=16
[cpu]
core=auto
cycles=fixed 20000
[autoexec]
mount r "{run}"
r:
cls
echo ORIG.EXE  the shipped 1993 binary
echo OURS.EXE  this reconstruction
echo.
"""

GO_BAT = """\
@echo off
rem GENERATED by runtest.py. Machine paths live here rather than in a
rem committed file, which is why this one is gitignored with the rest of run/.
"{exe}" -conf "{conf}"
"""


def machine(key):
    f = ROOT / "kit.local.toml"
    if not f.is_file():
        sys.exit("  no kit.local.toml -- it holds this machine's paths and is "
                 "not committed. See CLAUDE.md.")
    d = tomllib.load(io.open(f, "rb"))
    section, _, name = key.partition(".")
    try:
        return d[section][name]
    except KeyError:
        sys.exit("  kit.local.toml does not answer %s" % key)


def stale():
    """Sources newer than the rebuilt executable, if any."""
    exe = ROOT / "build" / "SOFTEL.EXE"
    if not exe.is_file():
        return ["build/SOFTEL.EXE does not exist -- run build.py first"]
    cut = exe.stat().st_mtime
    return ["src/%s is newer than the build" % p.name
            for p in sorted((ROOT / "src").glob("*.PAS"))
            if p.stat().st_mtime > cut]


def main(argv):
    bad = stale()
    if bad:
        print("  REFUSING to stage a stale run:")
        for line in bad:
            print("    %s" % line)
        print("    Watching the wrong program is not a measurement you can "
              "take back.")
        return 2

    RUN.mkdir(exist_ok=True)
    for name, src in STAGE:
        if not src.is_file():
            print("  missing %s" % src.relative_to(ROOT))
            return 2
        shutil.copy(src, RUN / name)

    conf = RUN / "DOSBOX.CONF"
    io.open(conf, "w", encoding="ascii", newline="\r\n").write(
        CONF.format(run=str(RUN)))

    exe = machine("dosbox.exe")
    go = RUN / "GO.BAT"
    io.open(go, "w", encoding="ascii", newline="\r\n").write(
        GO_BAT.format(exe=str(exe).replace("/", "\\"), conf=str(conf)))

    print("  staged run/ :")
    for name, src in STAGE:
        print("    %-12s %7d  <- %s"
              % (name, (RUN / name).stat().st_size, src.relative_to(ROOT)))
    print("    DOSBOX.CONF, GO.BAT    generated")
    print("\n  run\\GO.BAT launches it: R: is mounted and you land at R:\\")

    if "--print" in argv:
        return 0
    return subprocess.call([str(go)], cwd=str(RUN))


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
